apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
    #Puxar as variaveis no configmap de forma indivudal#   
    #env: 
      #- name: MYSQL_ROOT_PASSWORD
      #  valueFrom:
      #    conmfigMapKeyRef:
      #    name: db-configmap
      #    key: MYSQL_ROOT_PASSWORD

    #Puxar as variaveis do configmap todas de uma vez
      envFrom:
        - configMapRef:
            name: db-configmap

        
